### ISSUE TITLE
Metal compile error from concedo_experimental branch

### ISSUE THREAD

**Issue by beebopkim** [LostRuins/koboldcpp#629]
branch: concedo_experimental
commit: d42f1ef1f9b5cd91862f4ae8bdbaf7b74031afe1

What I had done is just run ```LLAMA_METAL=1 make```, and below error was happened.

```
ggml-metal.m:2251:64: error: no member named 'command_buffers' in 'struct ggml_metal_context'
                NSError *error = (MTLCommandBufferError) [ctx->command_buffers[i] error];
                                                          ~~~  ^
```

**Comment by LostRuins** [comment]
Sorry about that, was a bad merge. Can you pull and try again?

**Comment by beebopkim** [comment]
That's okay because it is the development branch. Thanks for your fast response. 👍

**Comment by beebopkim** [comment]
Error resolved.
